project:
  type: website

website:
  title: "SOBRU"
  announcement:    
    icon: balloon-fill
    dismissable: true
    content: "**Info** - Disse sidene er i utviklingsfasen"
    type: primary
    position: below-navbar
  navbar:
    logo: "img/USN_lilla.png"
    left:
      - href: index.qmd
        text: Hjem
      - href: infograf.qmd
        text: NEET i v√•r region
      - href: ny_dashboard.qmd
        text: Kart
      - href: shiny.qmd
        text: Interaktivt kart med shiny
      - href: info2.qmd
        text: Utvikling over tid
      - href: sankey.qmd
        text: Flytskjema
      - href: about.qmd
        text: Om
       

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true


editor: visual

